name: Superlinter
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1.5.0
        with:
          haxe-version: 4.3.0
      - name: Lint Haxe
        run: |
          haxelib install haxelint
          haxelib run haxelint -s source 
          haxelib run haxelint -s Preloader.hx
